# Generated by Django 5.2.8 on 2025-11-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
