# Generated by Django 5.2.8 on 2025-12-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_borrowrecord_fine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
