# Generated by Django 5.2.8 on 2025-12-03 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_borrowrecord_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='borrow_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
